baseURL = "https://anth2o.github.io/anth2o"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"
title = "Antoine Hoorelbeke"

[params]
  avatarURL = "https://avatars.githubusercontent.com/u/33425718?v=4"
  avatarAltText = "avatar"
  description = "Software engineer"
  footer = "Still in construction 🚧"

  socialIcons = [
    {name = "github", url = "https://github.com/anth2o"},
    {name = "linkedin", url = "https://www.linkedin.com/in/antoine-hoorelbeke-3953a390/"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/8205168/antoine"},
  ]
[menu]  
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    name = "Jobs"
    url = "/jobs/"
    weight = 2
    pre = "<span data-feather='briefcase'></span>"

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
    pre = "<span data-feather='code'></span>"

  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 4
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/anth2o"
    weight = 5
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/antoine-hoorelbeke-3953a390/"
    weight = 6
    pre = "<span data-feather='linkedin'></span>"
