name: PR Workflows

# Run action on pull request event
on: [pull_request]


jobs:
  # Build exampleSite
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4.2.2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node modules
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: |
        cd exampleSite
        hugo --minify

  # Run linter
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node modules
      run: npm install

    - name: Lint
      run: |
        npm run lint

  # Check for any broken links
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@v4.2.2
    # run markdown linter
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
